version: '3'

services:
  ansible:
    container_name: ansible
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./ansible:/ansible2

  postgres:
    image: postgres:14.7
    restart: always
    user: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  clickhouse:
    image: clickhouse/clickhouse-server:23.3.8.21-alpine
    volumes:
      - clickhouse-data:/var/lib/clickhouse/
    environment:
      - CLICKHOUSE_USER=clickhouse
      - CLICKHOUSE_PASSWORD=clickhouse
    ports:
      - "8123:8123"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://127.0.0.1:8123/ping || exit 1
      interval: 10s
      start_period: 10s
      timeout: 3s
      retries: 3

volumes:
  postgres-data:
    name: "Postgres_data"
  clickhouse-data:
    name: "ClickHouse_data"
